import { z } from "zod"

export const inputParamsSchema = {
  "surname": z.string().describe("Search for Learners by surname").optional(),
  "firstNames": z.string().describe("Search for Learners by first names").optional(),
  "sex": z.string().describe("Search for Learners by sex").optional(),
  "learningStatus": z.enum(["All","InLearningToday","InLearningAndLastYearLeavers","InLearningAndRecentLeavers","InLearningAndYetToStart","YetToStart","RecentLeavers","RecentAdded","AllLeavers","PastExpectedEnd"]).describe("Search for Learners by learning status").optional(),
  "status": z.string().describe("Search for Learners by status").optional(),
  "workflow": z.string().describe("Search for Learners by workflow").optional(),
  "workflowStatus": z.string().describe("Search for Learners by workflow status").optional(),
  "workflowSubStatus": z.string().describe("Search for Learners by workflow sub status").optional(),
  "qualificationPlan": z.string().describe("Search for Learners by qualification plan").optional(),
  "site": z.string().describe("Search for Learners by site").optional(),
  "subcontractorCode": z.string().describe("Search for Learners by subcontractor code").optional(),
  "nINumber": z.string().describe("Search for Learners by national insurance number").optional(),
  "postcode": z.string().describe("Search for Learners by postcode").optional(),
  "uLN": z.string().describe("Search for Learners by ULN").optional(),
  "mainOfficer": z.string().describe("Search for Learners by main officer").optional(),
  "dateOfBirth": z.string().datetime({ offset: true }).describe("Search for Learners by date of birth").optional(),
  "employer": z.string().describe("Search for Learners by Employer").optional(),
  "pONumber": z.string().describe("Search for Learners by PO number").optional(),
  "providerIdent": z.string().describe("Search for Learners by their Provider Assigned ID").optional(),
  "learnerReferenceNumber": z.string().describe("Search for Learners by their LRN (Learner Reference Number)").optional(),
  "createdSince": z.string().datetime({ offset: true }).describe("Search for Learners created since a given date").optional(),
  "modifiedSince": z.string().datetime({ offset: true }).describe("Search for Learners modified by another system since a given date").optional(),
  "plannedStartAfter": z.string().datetime({ offset: true }).describe("Search for Learners in learning on or before a given date").optional(),
  "plannedStartBefore": z.string().datetime({ offset: true }).describe("Search for Learners starting on or after a given date").optional(),
  "expectedEndAfter": z.string().datetime({ offset: true }).describe("Search for Learners expected to be ending on or after a given date").optional(),
  "expectedEndBefore": z.string().datetime({ offset: true }).describe("Search for Learners expected to be ending on or before a given date").optional(),
  "sortBy": z.enum(["Surname","FirstNames","StartDate","ExpectedEnd","ActualEnd","Created","InternalID"]).describe("Sort results by").optional(),
  "sortDirection": z.enum(["Assending","Descending"]).describe("Sort Direction").optional(),
  "pageNumber": z.number().int().describe("Page Number").optional(),
  "pageSize": z.number().int().gte(5).lte(1000).describe("Page Size").optional()
}