import { z } from "zod"

export const inputParamsSchema = {
  "id": z.string().describe("The Learners ident"),
  "b_id": z.string().min(1).describe("Required. Learner's identifier"),
  "title": z.string().nullable().describe("Learner's title").optional(),
  "firstNames": z.string().min(1).describe("Required. Learner's first names"),
  "preferredFirstName": z.string().max(30).nullable().describe("Maximum length: 30. Learner's preferred first name").optional(),
  "surname": z.string().min(1).describe("Required. Learner's surname"),
  "email": z.string().nullable().describe("Learner's email address").optional(),
  "risk": z.string().nullable().describe("Learner's risk information").optional(),
  "address": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `address` to the tool, first call the tool `expandSchema` with \"/properties/address\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>").optional(),
  "ward": z.string().nullable().describe("Learner's ward").optional(),
  "homePhone": z.string().nullable().describe("Learner's home phone number").optional(),
  "mobile": z.string().nullable().describe("Learner's mobile phone number").optional(),
  "username": z.string().nullable().describe("Learner's username").optional(),
  "userID": z.string().nullable().describe("Learner's user ID").optional(),
  "allowedContactMethods": z.array(z.string()).nullable().describe("List of allowed contact methods for the learner").optional(),
  "preferredContactMethod": z.string().nullable().describe("Preferred contact method for the learner").optional(),
  "dateOfBirth": z.string().datetime({ offset: true }).nullable().describe("Learner's date of birth").optional(),
  "sex": z.string().min(1).describe("Required. Learner's sex"),
  "ethnicity": z.string().nullable().describe("Learner's ethnicity").optional(),
  "niNumber": z.string().nullable().describe("Learner's National Insurance Number").optional(),
  "ilrDisability": z.string().nullable().describe("Learner's Individual Learning Record (ILR) disability information").optional(),
  "lldDs": z.array(z.string()).nullable().describe("List of Learning Difficulties and/or Disabilities (LLDDs) for the learner").optional(),
  "primaryLLDD": z.string().nullable().describe("Learner's primary LLDD").optional(),
  "nextOfKinName": z.string().nullable().describe("Name of the next of kin for the learner").optional(),
  "nextOfKinRelationship": z.string().nullable().describe("Relationship with the next of kin for the learner").optional(),
  "nextOfKinPhone": z.string().nullable().describe("Phone number of the next of kin for the learner").optional(),
  "nextOfKinPhone2": z.string().nullable().describe("Second phone number of the next of kin for the learner").optional(),
  "nextOfKinEmail": z.string().nullable().describe("Email address of the next of kin for the learner").optional(),
  "otherSystemID": z.string().nullable().describe("ID from another system for the learner").optional(),
  "providerIdent": z.string().nullable().describe("Provider identifier for the learner").optional(),
  "mainOfficer": z.string().nullable().describe("Main officer assigned to the learner").optional(),
  "recruitmentOfficer": z.string().nullable().describe("Recruitment officer assigned to the learner").optional(),
  "mentorOfficer": z.string().nullable().describe("Mentor officer assigned to the learner").optional(),
  "plannedStart": z.string().datetime({ offset: true }).nullable().describe("Planned start date for the learner").optional(),
  "expectedEnd": z.string().datetime({ offset: true }).nullable().describe("Expected end date for the learner").optional(),
  "countryOfDomicile": z.string().nullable().describe("Country of domicile for the learner").optional(),
  "site": z.string().nullable().describe("Site information for the learner").optional(),
  "uln": z.string().nullable().describe("Unique Learner Number (ULN) for the learner").optional(),
  "restrictedUseIndicator": z.string().nullable().describe("Restricted use indicator for the learner").optional(),
  "gcseMath": z.string().nullable().describe("GCSE Math qualification status for the learner").optional(),
  "gcseEnglish": z.string().nullable().describe("GCSE English qualification status for the learner").optional(),
  "qualificationPlan": z.string().nullable().describe("Qualification plan for the learner").optional()
}