import { z } from "zod"

export const inputParamsSchema = {
  "bookId": z.string().describe("The book's id."),
  "isStpV2Enabled": z.boolean().nullable().describe("Indicates whether Single Touch Payroll report version 2 is enabled.").optional(),
  "isPreparingForStpV2": z.boolean().nullable().describe("Indicates whether the book is being prepared for Single Touch Payroll version 2.").optional(),
  "legalContact": z.object({ "firstName": z.string().nullable().describe("The first name of legal contact.").optional(), "lastName": z.string().nullable().describe("The last name of legal contact.").optional(), "title": z.string().nullable().describe("The legal contact's title.").optional() }).strict().describe("The payroll settings' legal contact details to patch.").nullable().describe("The payroll settings' legal contact.").optional(),
  "payrollSetup": z.object({ "copyPayItemsFromPreviousPay": z.boolean().nullable().describe("Indicates whether the pay run copies pay items from previous pay (overrides default pay items).").optional(), "trackProjectCost": z.boolean().nullable().describe("Indicates whether it tracks project cost.\n            ").optional(), "allowPayRatesEditInPayRuns": z.boolean().nullable().describe("Indicates whether it allows editing of pay rates on pay runs.").optional(), "optionalEmailPasswordProtection": z.boolean().nullable().describe("Indicates whether it enables password protection for emailing pay slips and payment summaries.").optional(), "displayYTDOnPayrun": z.boolean().nullable().describe("Indicates whether it displays YTD amounts on pay run.").optional() }).strict().describe("A book's payroll setup to patch.").nullable().describe("The payroll setup details.").optional(),
  "defaultAccounts": z.object({ "payWitholdingAmountToSupplier": z.boolean().nullable().describe("Indicates whether pays to supplier through accounts payable.").optional(), "expenseAccount": z.string().nullable().describe("The expense account.").optional(), "expenseAccountForCompanySuperContributions": z.string().nullable().describe("The expense account for company super contributions.").optional(), "liabilityAccount": z.string().nullable().describe("The liability account.").optional(), "liabilityAccountForWithholdingAmounts": z.string().nullable().describe("The liability account for withholding amount.").optional(), "supplierForWithholdingAmounts": z.string().nullable().describe("Supplier for withholding amounts.").optional() }).strict().describe("The payroll settings' default accounts to patch.").nullable().describe("The default payroll accounts.").optional(),
  "defaultPayments": z.object({ "roundToNearest": z.enum(["NoRounding","FiveCents","TenCents","FiftyCents","OneDollar"]).describe("Rounding settings of payments.").nullable().describe("Rounding settings of payments.").optional(), "expenseAccountForRounding": z.string().nullable().describe("Expense account for rounding of cash payments.").optional() }).strict().describe("The details of payroll default payments to patch.").nullable().describe("The default payroll payments.").optional(),
  "automaticPayrollPayments": z.boolean().nullable().describe("Indicates whether makes payroll salary and wages payments when users finish each pay run.").optional(),
  "defaultBankAccounts": z.object({ "directCreditPaymentsBankAccount": z.string().nullable().describe("The direct credit payment bank account.").optional(), "cashPaymentsBankAccount": z.string().nullable().describe("The cash payments account.").optional(), "superPaymentsBankAccount": z.string().nullable().describe("The super payment bank account.").optional() }).strict().describe("The details of payroll default bank accounts to patch.").nullable().describe("The default payroll bank accounts.").optional(),
  "isReducingOteHoursEnabled": z.boolean().describe("Indicates whether reducing ote hours is enabled.").optional()
}