export const OPENAPI_URL = "https://data.bka.gv.at/ris/api/v2.6/Content/OGD-RIS_API.yml"
export const SERVER_NAME = "RIS - Österreichisches Rechts Informations System"
export const SERVER_VERSION = "0.0.1"
export const OPERATION_FILES_RELATIVE = [
  "./tools/postquerybundesrecht_brkons/index.js",
  "./tools/postquerybundesrecht_bgblauth/index.js",
  "./tools/postquerybundesrecht_bgblpdf/index.js",
  "./tools/postquerybundesrecht_bgblalt/index.js",
  "./tools/postquerybundesrecht_begut/index.js",
  "./tools/postquerybundesrecht_regv/index.js",
  "./tools/postquerybundesrecht_erv/index.js",
  "./tools/postquerylandesrecht_lrkons/index.js",
  "./tools/postquerylandesrecht_lgblauth/index.js",
  "./tools/postquerylandesrecht_lgbl/index.js",
  "./tools/postquerylandesrecht_lgblno/index.js",
  "./tools/postquerylandesrecht_vbl/index.js",
  "./tools/postquerybezirke_bvb/index.js",
  "./tools/postquerygemeinden_gr/index.js",
  "./tools/postquerygemeinden_gra/index.js",
  "./tools/postqueryjudikatur_vfgh/index.js",
  "./tools/postqueryjudikatur_vwgh/index.js",
  "./tools/postqueryjudikatur_normenliste/index.js",
  "./tools/postqueryjudikatur_justiz/index.js",
  "./tools/postqueryjudikatur_bvwg/index.js",
  "./tools/postqueryjudikatur_lvwg/index.js",
  "./tools/postqueryjudikatur_dsk/index.js",
  "./tools/postqueryjudikatur_dok/index.js",
  "./tools/postqueryjudikatur_pvak/index.js",
  "./tools/postqueryjudikatur_gbk/index.js",
  "./tools/postqueryjudikatur_uvs/index.js",
  "./tools/postqueryjudikatur_asylgh/index.js",
  "./tools/postqueryjudikatur_ubas/index.js",
  "./tools/postqueryjudikatur_umse/index.js",
  "./tools/postqueryjudikatur_bks/index.js",
  "./tools/postqueryjudikatur_verg/index.js",
  "./tools/postquerysonstige_pruefgewo/index.js",
  "./tools/postquerysonstige_avsv/index.js",
  "./tools/postquerysonstige_spg/index.js",
  "./tools/postquerysonstige_avn/index.js",
  "./tools/postquerysonstige_kmger/index.js",
  "./tools/postquerysonstige_upts/index.js",
  "./tools/postquerysonstige_mrp/index.js",
  "./tools/postquerysonstige_erlaesse/index.js"
]