import { z } from "zod"

export const inputParamsSchema = {
  "title": z.string().nullable().describe("Applicant's Title").optional(),
  "firstNames": z.string().min(1).describe("Applicant's First Names"),
  "preferredFirstName": z.string().nullable().describe("Applicant's Preferred First Name").optional(),
  "surname": z.string().min(1).describe("Applicant's Surname"),
  "previousSurname": z.string().nullable().describe("Applicant's Previous Surname").optional(),
  "email": z.string().nullable().describe("Applicant's Email").optional(),
  "risk": z.string().nullable().describe("Applicant's Risk").optional(),
  "address": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `address` to the tool, first call the tool `expandSchema` with \"/properties/address\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>").optional(),
  "homePhone": z.string().nullable().describe("Applicant's Home Phone Number").optional(),
  "mobile": z.string().nullable().describe("Applicant's Mobile Phone Number").optional(),
  "picsUsername": z.string().nullable().describe("Applicant's PICS Username").optional(),
  "allowedContactMethods": z.array(z.string()).nullable().describe("Applicant's Allowed Contact Method Codes").optional(),
  "preferredContactMethod": z.string().nullable().describe("Applicant's Preferred Contact Method Code").optional(),
  "dateOfBirth": z.string().datetime({ offset: true }).nullable().describe("Applicant's Date Of Birth").optional(),
  "sex": z.string().nullable().describe("Applicant's Sex").optional(),
  "ethnicity": z.string().nullable().describe("Applicant's Ethnicity").optional(),
  "niNumber": z.string().nullable().describe("Applicant's NINumber").optional(),
  "learnerReferenceNumber": z.string().nullable().describe("Applicant's Learner Reference Number").optional(),
  "ilrDisability": z.string().nullable().describe("Applicant's ILR Disability").optional(),
  "lldDs": z.array(z.string()).nullable().describe("Applicant's LLDDs").optional(),
  "primaryLLDD": z.string().nullable().describe("Applicant's Primary LLDD").optional(),
  "householdSituation": z.array(z.string()).nullable().describe("Applicant's Household Situation").optional(),
  "nextOfKinName": z.string().nullable().describe("Applicant's Next Of Kin Name").optional(),
  "nextOfKinRelationship": z.string().nullable().describe("Applicant's Next Of Kin Relationship").optional(),
  "nextOfKinPhone": z.string().nullable().describe("Applicant's Next Of Kin Phone Number").optional(),
  "nextOfKinPhone2": z.string().nullable().describe("Applicant's Next Of Kin Phone Number 2").optional(),
  "nextOfKinEmail": z.string().nullable().describe("Applicant's Next Of Kin Email").optional(),
  "otherSystemID": z.string().nullable().describe("Applicant's Other System ID").optional(),
  "providerIdent": z.string().nullable().describe("Applicant's Provider Ident").optional(),
  "mainOfficer": z.string().nullable().describe("Applicant's Main Officer Code").optional(),
  "recruitmentOfficer": z.string().nullable().describe("Applicant's Recruitment Officer Code").optional(),
  "mentorOfficer": z.string().nullable().describe("Applicant's Mentor Officer Code").optional(),
  "plannedStart": z.string().datetime({ offset: true }).nullable().describe("Applicant's Planned Start Date").optional(),
  "expectedEnd": z.string().datetime({ offset: true }).nullable().describe("Applicant's Expected End Date").optional(),
  "countryOfDomicile": z.string().nullable().describe("Applicant's Country Of Domicile").optional(),
  "site": z.string().nullable().describe("Applicant's Site Code").optional(),
  "uln": z.string().nullable().describe("Applicant's ULN").optional(),
  "restrictedUseIndicator": z.string().nullable().describe("Applicant's Restricted Use Indicator").optional(),
  "gcseMath": z.string().nullable().describe("Applicant's GCSE Math").optional(),
  "gcseEnglish": z.string().nullable().describe("Applicant's GCSE English").optional(),
  "qualificationPlan": z.string().nullable().describe("Applicant's Qualification Plan Code").optional(),
  "act": z.string().nullable().describe("Applicant's ACT").optional(),
  "vatStatus": z.string().nullable().describe("Applicant's VATStatus").optional(),
  "asStatus": z.string().nullable().describe("Applicant's Apprenticeship Service Status").optional(),
  "asCohort": z.string().nullable().describe("Applicant's Apprenticeship Service Cohort").optional(),
  "bksbUsername": z.string().nullable().describe("Applicant's BKSB Username").optional(),
  "workflow": z.string().nullable().describe("Applicant's Workflow").optional(),
  "employerCode": z.string().nullable().describe("Applicant's Employer Code").optional(),
  "recruitmentAgencyCode": z.string().nullable().describe("Applicant's Recruitment Agency Code").optional(),
  "opportunityID": z.number().int().nullable().describe("Applicant's Opportunity ID").optional()
}