import { z } from "zod"

export const inputParamsSchema = {
  "bookId": z.string().describe("The book's id."),
  "supplier": z.string().min(1).describe("The supplier that is being paid."),
  "paymentDate": z.string().datetime({ offset: true }).min(1).describe("The date of the payment"),
  "ledgerAccount": z.string().nullable().describe("The id or name of the bank/cash/credit account where the money was received.").optional(),
  "paymentMethod": z.string().nullable().describe("The id or name of the payment method used.").optional(),
  "reference": z.string().max(200).nullable().describe("The payment reference.").optional(),
  "notes": z.string().max(255).nullable().describe("Notes related to the payment").optional(),
  "reconciliationStatus": z.enum(["Uncleared","Cleared","Reconciled"]).describe("Reconciliation status.").nullable().describe("The payments's reconciliation status.\nNote that this can only be initially set to Cleared or Uncleared and that it can only be updated via a bank reconciliation.").optional(),
  "internalNotes": z.string().max(400).nullable().describe("Internal Notes related to the payment").optional(),
  "accountsPayableLedgerAccount": z.string().nullable().describe("The accounts payable ledger account.\n_Note:_ It is not currently possible to create multiple Accounts Payable accounts so this field is read-only and will be ignored.").readonly().optional(),
  "classification": z.string().nullable().describe("The classification.").optional(),
  "transactionLinks": z.array(z.object({ "transactionType": z.enum(["Estimate","Expense","Timesheet","Receipt","CreditNote","Payment","Invoice","Journal","Bill","PayRun","ReversedJournal","ReversalJournal","BankPayment","SupplierCreditNote","ExpenseLineItem","JournalLineItem"]).describe("Type of transaction linked to an invoice or bill.").describe("The type of linked transaction."), "transactionId": z.string().min(1).describe("The unique id of the linked transaction."), "transactionAmount": z.number().describe("The transaction's amount.") }).strict().describe("Details of a transaction to link to a payment")).nullable().describe("Details of transactions that the payment should be allocated to.").optional(),
  "lineItems": z.array(z.object({ "lineNumber": z.number().int().describe("The line number."), "project": z.string().nullable().describe("The id or full name of the project that the line item relates to.\nNote that the full name includes the name(s) of any parent project(s) separated by colons."), "itemDetails": z.object({ "item": z.string().min(1).describe("The id or full name of the item that the line relates to.\nNote that the full name includes the name(s) of any parent item(s) separated by colons."), "price": z.number().nullable().describe("The price of each item including or excluding tax (depending on the `amountTaxStatus`)."), "quantity": z.number().nullable().describe("The quantity purchased."), "discountAmount": z.number().nullable().describe("The total discount for the line item."), "discountPercent": z.number().nullable().describe("The discount percentage for the line item."), "billableId": z.string().nullable().describe("The id related to a billable line item.").optional() }).strict().describe("Details of an item used on an payment line item.").nullable().describe("Details of an item used on an invoice line item.\nThis must be omitted if `accountDetails` have been provided."), "accountDetails": z.object({ "ledgerAccount": z.string().min(1).describe("The id or full name of the ledger account that the line relates to.\nNote that the full name includes the name(s) of any parent account(s) separated by colons."), "quantity": z.number().nullable().describe("The quantity purchased."), "amount": z.number().nullable().describe("The amount including or excluding tax (depending on the `amountTaxStatus`).") }).strict().describe("Details of an account used on an payment line item.").nullable().describe("Details of an account used on an invoice line item.\nThis must be omitted if `itemDetails` have been provided."), "description": z.string().max(1000).nullable().describe("The description of the line."), "taxRate": z.string().nullable().describe("The tax rate."), "taxAmount": z.number().nullable().describe("The tax amount.") }).strict().describe("Details of a payment line item to create or update.")).nullable().describe("The individual items that make up the payment").optional(),
  "totalAmount": z.number().describe("The total amount of the payment applied")
}