import { z } from "zod"

export const inputParamsSchema = {
  "slug": z.string(),
  "id": z.union([z.string(), z.null()]).optional(),
  "userId": z.string().optional(),
  "householdId": z.string().optional(),
  "groupId": z.string().optional(),
  "name": z.union([z.string(), z.null()]).optional(),
  "b_slug": z.string().optional(),
  "image": z.union([z.any(), z.null()]).optional(),
  "recipeServings": z.number().optional(),
  "recipeYieldQuantity": z.number().optional(),
  "recipeYield": z.union([z.string(), z.null()]).optional(),
  "totalTime": z.union([z.string(), z.null()]).optional(),
  "prepTime": z.union([z.string(), z.null()]).optional(),
  "cookTime": z.union([z.string(), z.null()]).optional(),
  "performTime": z.union([z.string(), z.null()]).optional(),
  "description": z.union([z.string(), z.null()]).optional(),
  "recipeCategory": z.union([z.array(z.object({ "id": z.union([z.string(), z.null()]).optional(), "groupId": z.union([z.string(), z.null()]).optional(), "name": z.string(), "slug": z.string() })), z.null()]).optional(),
  "tags": z.union([z.array(z.object({ "id": z.union([z.string(), z.null()]).optional(), "groupId": z.union([z.string(), z.null()]).optional(), "name": z.string(), "slug": z.string() })), z.null()]).optional(),
  "tools": z.array(z.object({ "id": z.string(), "groupId": z.union([z.string(), z.null()]).optional(), "name": z.string(), "slug": z.string(), "householdsWithTool": z.array(z.string()) })).optional(),
  "rating": z.union([z.number(), z.null()]).optional(),
  "orgURL": z.union([z.string(), z.null()]).optional(),
  "dateAdded": z.union([z.string().date(), z.null()]).optional(),
  "dateUpdated": z.union([z.string().datetime({ offset: true }), z.null()]).optional(),
  "createdAt": z.union([z.string().datetime({ offset: true }), z.null()]).optional(),
  "update_at": z.union([z.string().datetime({ offset: true }), z.null()]).optional(),
  "lastMade": z.union([z.string().datetime({ offset: true }), z.null()]).optional(),
  "recipeIngredient": z.array(z.object({ "quantity": z.union([z.number(), z.null()]), "unit": z.union([z.object({ "id": z.string(), "name": z.string(), "pluralName": z.union([z.string(), z.null()]).optional(), "description": z.string(), "extras": z.union([z.record(z.any()), z.null()]), "fraction": z.boolean(), "abbreviation": z.string(), "pluralAbbreviation": z.union([z.string(), z.null()]), "useAbbreviation": z.boolean(), "aliases": z.array(z.object({ "name": z.string() })), "createdAt": z.union([z.string().datetime({ offset: true }), z.null()]).optional(), "update_at": z.union([z.string().datetime({ offset: true }), z.null()]).optional() }), z.object({ "id": z.union([z.string(), z.null()]).optional(), "name": z.string(), "pluralName": z.union([z.string(), z.null()]).optional(), "description": z.string(), "extras": z.union([z.record(z.any()), z.null()]), "fraction": z.boolean(), "abbreviation": z.string(), "pluralAbbreviation": z.union([z.string(), z.null()]), "useAbbreviation": z.boolean(), "aliases": z.array(z.object({ "name": z.string() })) }), z.null()]).optional(), "food": z.union([z.object({ "id": z.string(), "name": z.string(), "pluralName": z.union([z.string(), z.null()]).optional(), "description": z.string(), "extras": z.union([z.record(z.any()), z.null()]), "labelId": z.union([z.string(), z.null()]).optional(), "aliases": z.array(z.object({ "name": z.string() })), "householdsWithIngredientFood": z.array(z.string()), "label": z.union([z.object({ "name": z.string(), "color": z.string(), "groupId": z.string(), "id": z.string() }), z.null()]).optional(), "createdAt": z.union([z.string().datetime({ offset: true }), z.null()]).optional(), "update_at": z.union([z.string().datetime({ offset: true }), z.null()]).optional() }), z.object({ "id": z.union([z.string(), z.null()]).optional(), "name": z.string(), "pluralName": z.union([z.string(), z.null()]).optional(), "description": z.string(), "extras": z.union([z.record(z.any()), z.null()]), "labelId": z.union([z.string(), z.null()]).optional(), "aliases": z.array(z.object({ "name": z.string() })), "householdsWithIngredientFood": z.array(z.string()) }), z.null()]).optional(), "note": z.union([z.string(), z.null()]), "isFood": z.union([z.boolean(), z.null()]).optional(), "disableAmount": z.boolean(), "display": z.string(), "title": z.union([z.string(), z.null()]).optional(), "originalText": z.union([z.string(), z.null()]).optional(), "referenceId": z.string().uuid().optional() })).optional(),
  "recipeInstructions": z.union([z.array(z.object({ "id": z.union([z.string().uuid(), z.null()]).optional(), "title": z.union([z.string(), z.null()]), "summary": z.union([z.string(), z.null()]), "text": z.string(), "ingredientReferences": z.array(z.object({ "referenceId": z.union([z.string(), z.null()]).optional() }).describe("A list of ingredient references.")) })), z.null()]).optional(),
  "nutrition": z.union([z.object({ "calories": z.union([z.string(), z.null()]).optional(), "carbohydrateContent": z.union([z.string(), z.null()]).optional(), "cholesterolContent": z.union([z.string(), z.null()]).optional(), "fatContent": z.union([z.string(), z.null()]).optional(), "fiberContent": z.union([z.string(), z.null()]).optional(), "proteinContent": z.union([z.string(), z.null()]).optional(), "saturatedFatContent": z.union([z.string(), z.null()]).optional(), "sodiumContent": z.union([z.string(), z.null()]).optional(), "sugarContent": z.union([z.string(), z.null()]).optional(), "transFatContent": z.union([z.string(), z.null()]).optional(), "unsaturatedFatContent": z.union([z.string(), z.null()]).optional() }), z.null()]).optional(),
  "settings": z.union([z.object({ "public": z.boolean(), "showNutrition": z.boolean(), "showAssets": z.boolean(), "landscapeView": z.boolean(), "disableComments": z.boolean(), "disableAmount": z.boolean(), "locked": z.boolean() }), z.null()]).optional(),
  "assets": z.union([z.array(z.object({ "name": z.string(), "icon": z.string(), "fileName": z.union([z.string(), z.null()]).optional() })), z.null()]).optional(),
  "notes": z.union([z.array(z.object({ "title": z.string(), "text": z.string() })), z.null()]).optional(),
  "extras": z.union([z.record(z.any()), z.null()]).optional(),
  "comments": z.union([z.array(z.object({ "recipeId": z.string(), "text": z.string(), "id": z.string(), "createdAt": z.string().datetime({ offset: true }), "update_at": z.string().datetime({ offset: true }), "userId": z.string(), "user": z.object({ "id": z.string(), "username": z.union([z.string(), z.null()]).optional(), "admin": z.boolean(), "fullName": z.union([z.string(), z.null()]).optional() }) })), z.null()]).optional(),
  "accept-language": z.union([z.string(), z.null()]).optional()
}