import { z } from "zod"

export const inputParamsSchema = {
  "full_name": z.union([z.string().min(1).max(255), z.null()]).optional(),
  "username": z.union([z.string().min(3).max(30).describe("Only alphanumeric characters are allowed: `a-z` `A-Z`, `0-9`. If the username starts with `^`, it is autogenerated -> consider masking."), z.null()]).optional(),
  "is_public": z.union([z.boolean(), z.null()]).describe("Enable if the user can be found by username.").optional(),
  "avatar_image_id": z.union([z.string().uuid(), z.null()]).optional(),
  "cover_image_id": z.union([z.string().uuid(), z.null()]).optional()
}