import { z } from "zod"

export const inputParamsSchema = {
  "bookId": z.string().describe("The book's id."),
  "taxRegistered": z.boolean().nullable().describe("Indicates whether you registered for tax.").optional(),
  "reportingBasis": z.enum(["Accrual","Cash","Hybrid"]).describe("The sales figures type of tax. Hybrid is for NZ books only.").nullable().describe("The tax reporting basis type.").optional(),
  "amountTaxStatus": z.enum(["Inclusive","Exclusive"]).describe("The sales figures type of tax.").nullable().describe("Indicates whether sales figures are shown in the gross sales or the net sales.").optional(),
  "defaultSalesTaxLedgerAccount": z.string().nullable().describe("Default tax account ledger for sales.").optional(),
  "defaultPurchasesTaxLedgerAccount": z.string().nullable().describe("Default tax account ledger for purchases.").optional(),
  "taxAmountEditable": z.boolean().nullable().describe("Indicates whether allows users to edit tax amounts.").optional(),
  "chooseAmountTaxStatus": z.boolean().nullable().describe("Indicates whether a user can choose if amounts include or exclude tax.").optional(),
  "basSettings": z.object({ "reportingPeriodType": z.enum(["Monthly","QuarterlyOption1GstReportQuarterly","QuarterlyOption2GstQuarterlyReportAnnually","QuarterlyOption3GstInstalmentQuarterly","Annually"]).describe("The BAS reporting period.").describe("The BAS reporting period.").optional(), "simplerBAS": z.boolean().nullable().describe("Indicates whether its a simpler BAS. Simpler BAS is only applicable for business reporting GST on Monthly, Annual or quarterly basis (option 1: Calculate GST and report quarterly).").optional(), "amountTaxStatus": z.enum(["Inclusive","Exclusive"]).describe("The sales figures type of tax.").nullable().describe("Show amounts reported in BAS as inclusive or exclusive.").optional(), "fbt": z.boolean().nullable().describe("Indicates whether Fringe Benefits Tax (FBT) applies to the business.").optional(), "ftc": z.boolean().nullable().describe("Indicates whether Fuel Tax Credits (FTC) applies to the business.").optional(), "lct": z.boolean().nullable().describe("Indicates whether Luxury Car Tax (LCT) applies to the business.").optional(), "paygiPayQuarterly": z.boolean().nullable().describe("Indicates whether Pay As You Go Income Tax Instalment (PAYG I) applies to the business. Pay PAYG instalment quarterly.").optional(), "paygiCalculateUsingIncomeTimesRate": z.boolean().nullable().describe("Indicates whether Pay As You Go Income Tax Instalment (PAYG I) applies to the business. Calculate PAYG instalment using income times rate.").optional(), "paygw": z.boolean().nullable().describe("Indicates whether Pay As You Go Tax Withheld (PAYG W) applies to the business.").optional(), "wet": z.boolean().nullable().describe("Indicates whether Wine Equalisation Tax (WET) applies to the business.").optional() }).strict().describe("BAS report settings to patch.").nullable().describe("The BAS reporting preference details.").optional(),
  "gstSettings": z.object({ "filingFrequency": z.enum(["Monthly","TwoMonthly","SixMonthly"]).describe("The GST filing frequency.").describe("The GST filing frequency.").optional(), "reportingPeriod": z.enum(["StartsFromJan","StartsFromFeb","StartsFromMar","StartsFromApr","StartsFromMay","StartsFromJun"]).describe("The GST reporting period.").describe("The GST reporting period.").optional(), "returnBasis": z.enum(["CalculateGSTFromGross","CalculateGrossFromGST"]).describe("The GST return basis.").describe("The GST return basis.").optional() }).strict().describe("GST report settings to patch.").nullable().describe("The GST reporting preference details.").optional(),
  "vatSettings": z.object({ "registrationNumber": z.string().nullable().describe("VAT registration number.").optional(), "scheme": z.enum(["Standard","Monthly","Annual"]).describe("HMRC VAT scheme.").nullable().describe("HMRC VAT scheme.").optional(), "periodGroup": z.enum(["MarJunSepDec","JulOctJanApr","AugNovFebMay"]).describe("VAT period ending group.").nullable().describe("VAT period ending group.").optional(), "flatRateScheme": z.enum(["Enabled","Disabled"]).describe("VAT flat rate scheme.").nullable().describe("VAT flat rate scheme.").optional(), "registeredSinceDate": z.string().datetime({ offset: true }).nullable().describe("VAT Registered since date.").optional(), "ecVatEnabled": z.boolean().nullable().describe("Activates EC VAT codes and flag on the VAT return that EC VAT is enabled.").optional(), "usePostponedVatAccounting": z.boolean().nullable().describe("Enables Postponed VAT Accounting codes.").optional() }).strict().describe("VAT report settings to patch.").nullable().describe("The VAT reporting preference details.").optional(),
  "emailSettings": z.object({ "bas": z.object({ "includeCc": z.boolean().nullable().describe("Indicates whether includes CC by default when emailing.").optional(), "ccAddress": z.string().nullable().describe("Default CC email address.").optional(), "includeBcc": z.boolean().nullable().describe("Indicates whether includes BCC by default when emailing.").optional(), "bccAddress": z.string().nullable().describe("Default BCC email address.").optional(), "emailSubject": z.string().nullable().describe("Default email subject.").optional(), "emailContent": z.string().nullable().describe("Default email content.").optional() }).strict().describe("The email template to patch.").nullable().describe("BAS default email settings.").optional() }).strict().describe("The book's tax email settings to patch.").nullable().describe("The email settings for tax.").optional()
}