import { z } from "zod"

export const inputParamsSchema = {
  "name": z.string().min(3).max(100).describe("Nome descritivo da totalização"),
  "description": z.union([z.string().max(500), z.null()]).describe("Descrição detalhada").optional(),
  "source_tag_id": z.string().uuid().describe("ID do sensor que será totalizado"),
  "trigger_type": z.string(),
  "operation": z.string().optional(),
  "time_interval": z.union([z.enum(["minute","hour","day","week","month"]).describe("Intervalos de tempo para totalização"), z.null()]).describe("Intervalo de tempo").optional(),
  "time_interval_value": z.union([z.number().int().gte(1).lte(60), z.null()]).describe("Valor do intervalo (ex: a cada 2 horas)").optional(),
  "window_type": z.string().optional(),
  "fixed_hour_start": z.union([z.number().int().gte(0).lte(23), z.null()]).describe("Hora de início para janelas fixas (0-23)").optional(),
  "fixed_hour_end": z.union([z.number().int().gte(0).lte(23), z.null()]).describe("Hora de fim para janelas fixas (0-23)").optional(),
  "daily_start_time": z.union([z.string().regex(new RegExp("^([01]?[0-9]|2[0-3]):[0-5][0-9]$")), z.null()]).describe("Horário de início diário (HH:MM)").optional(),
  "daily_end_time": z.union([z.string().regex(new RegExp("^([01]?[0-9]|2[0-3]):[0-5][0-9]$")), z.null()]).describe("Horário de fim diário (HH:MM)").optional(),
  "weekly_start_day": z.union([z.number().int().gte(0).lte(6), z.null()]).describe("Dia da semana início (0=segunda, 6=domingo)").optional(),
  "weekly_end_day": z.union([z.number().int().gte(0).lte(6), z.null()]).describe("Dia da semana fim (0=segunda, 6=domingo)").optional(),
  "monthly_start_day": z.union([z.number().int().gte(1).lte(31), z.null()]).describe("Dia do mês início (1-31)").optional(),
  "monthly_end_day": z.union([z.number().int().gte(1).lte(31), z.null()]).describe("Dia do mês fim (1-31)").optional(),
  "custom_shifts": z.union([z.array(z.object({ "name": z.string().describe("Nome do turno"), "start": z.string().regex(new RegExp("^([01]?[0-9]|2[0-3]):[0-5][0-9]$")).describe("Horário de início (HH:MM)"), "end": z.string().regex(new RegExp("^([01]?[0-9]|2[0-3]):[0-5][0-9]$")).describe("Horário de fim (HH:MM)") }).describe("Schema para turno customizado")), z.null()]).describe("Turnos customizados").optional(),
  "window_timezone": z.string().describe("Timezone para cálculo das janelas").optional(),
  "allow_overlap": z.boolean().describe("Permitir janelas sobrepostas").optional(),
  "gap_tolerance_minutes": z.number().int().gte(0).lte(60).describe("Tolerância para gaps entre janelas (minutos)").optional(),
  "running_condition": z.union([z.string(), z.null()]).describe("Condição para considerar 'funcionando' (ex: '> 0.5')").optional(),
  "running_threshold": z.union([z.number(), z.null()]).describe("Valor limite para considerar funcionando").optional(),
  "state_values": z.union([z.record(z.string()), z.null()]).describe("Mapeamento valor->estado: {'1': 'running', '0': 'stopped', '3': 'maintenance'}").optional(),
  "idle_timeout_minutes": z.number().int().gte(1).lte(60).describe("Timeout para considerar parado (minutos)").optional(),
  "equipment_power_kw": z.union([z.number().gt(0), z.null()]).describe("Potência do equipamento em kW").optional(),
  "energy_price_kwh": z.union([z.number().gt(0), z.null()]).describe("Preço da energia em R$/kWh").optional(),
  "energy_tariff_config": z.union([z.record(z.any()), z.null()]).describe("Configuração de tarifas por horário").optional(),
  "trigger_tag_id": z.union([z.string().uuid(), z.null()]).describe("ID do sensor que dispara a totalização").optional(),
  "trigger_condition": z.union([z.enum(["==","!=",">",">=","<","<="]).describe("Condições para trigger baseado em sensor"), z.null()]).describe("Condição do trigger").optional(),
  "trigger_value": z.union([z.number(), z.null()]).describe("Valor que dispara a totalização").optional(),
  "reset_on_trigger": z.boolean().describe("Reset após cada totalização").optional(),
  "min_samples": z.number().int().gte(1).describe("Mínimo de amostras para calcular").optional(),
  "quality_filter": z.string().describe("Filtrar por qualidade dos dados").optional(),
  "store_intermediate_values": z.boolean().describe("Armazenar valores intermediários").optional(),
  "precision_digits": z.number().int().gte(0).lte(6).describe("Precisão decimal do resultado").optional(),
  "active": z.boolean().describe("Configuração ativa").optional()
}