import { z } from "zod"

export const inputParamsSchema = {
  "full_name": z.string().min(1).max(255),
  "dev_access_expiry_minutes": z.union([z.number().int(), z.null()]).optional(),
  "dev_refresh_expiry_minutes": z.union([z.number().int(), z.null()]).optional(),
  "phone": z.string().max(255),
  "otp_code": z.string(),
  "device": z.union([z.object({ "vendor_id": z.string().max(50).describe("Unique identifier for device."), "vendor_name": z.enum(["apple","android","other"]).describe("Used to determine which push notification provider to use."), "os_name": z.union([z.string().max(50), z.null()]).optional(), "os_version": z.union([z.string().max(255), z.null()]).optional(), "device_name": z.union([z.string().max(255), z.null()]).optional() }).describe("Input request DTO for creating a Device."), z.null()]).optional(),
  "username": z.union([z.string().min(3).max(30).describe("Only alphanumeric characters are allowed: `a-z` `A-Z`, `0-9`. If the username starts with `^`, it is autogenerated -> consider masking."), z.null()]).describe("If not provided, username will be generated from full name. If the usernames cannot be generated from full name, then it will be autogenerated, such that it will start with `^` followed by some hash.").optional(),
  "date_of_birth": z.string().datetime({ offset: true }).describe("Must be at least 16 years old.").optional()
}