import { z } from "zod"

export const inputParamsSchema = {
  "bookId": z.string().describe("The book's id."),
  "startDate": z.string().datetime({ offset: true }).min(1).describe("The first day of records for the book."),
  "lockOffDate": z.string().datetime({ offset: true }).nullable().describe("Transactions on or before this date cannot be changed.").optional(),
  "entity": z.string().nullable().describe("The id or name of the entity type of business.").optional(),
  "industry": z.string().nullable().describe("The id or name of the industry of business.").optional(),
  "category": z.string().nullable().describe("The id or name of the industry's category of business.").optional(),
  "businessType": z.string().nullable().describe("The id or name of the industry category's business type.").optional(),
  "replyToEmailAddress": z.string().max(100).nullable().describe("The email address used by clients when replying to emails sent from Reckon One.").optional(),
  "showEmailSentFrom": z.string().max(100).nullable().describe("The displayed name of sender in emails.").optional(),
  "bankDataRetrievalDays": z.number().int().gte(1).lte(365).describe("The number of most recent days bank data is retrieved for."),
  "generalDetails": z.object({ "companyName": z.string().max(255).nullable().describe("The company's business/trading name.").optional(), "legalName": z.string().max(255).nullable().describe("The name of the company that appears on legal documents.").optional(), "taxNumber": z.string().max(50).nullable().describe("The tax number of the company, for example, 'ABN/WPN' for AU and 'GST/IRD number' for NZ.").optional(), "branchNumber": z.string().max(10).nullable().describe("The branch number associated with the tax number.").optional(), "companyReference": z.string().nullable().describe("The company reference.").optional(), "businessNumber": z.string().max(13).nullable().describe("The business number of the company, for example, New Zealand Business Number (NZBN).").optional(), "isRegisteredEmployerOfWHM": z.boolean().describe("Whether the company is a registered WHM employer.").optional() }).strict().describe("Basic business details to update.").nullable().describe("General company details").optional(),
  "addresses": z.array(z.object({ "type": z.string().nullable().describe("The name or id of the address type.").optional(), "line1": z.string().nullable().describe("First line of address.").optional(), "line2": z.string().nullable().describe("Second line of address.").optional(), "line3": z.string().nullable().describe("Third line of address.").optional(), "town": z.string().nullable().describe("Town of address.").optional(), "suburb": z.string().nullable().describe("Suburb of address.").optional(), "state": z.string().nullable().describe("State of address.").optional(), "postcode": z.string().nullable().describe("Postcode of address.").optional(), "country": z.string().nullable().describe("Country of address.").optional(), "isInternational": z.string().nullable().describe("Indicates whether address within another country.").optional() }).strict().describe("An address to update.")).describe("List of addresses."),
  "contactDetails": z.object({ "contactName": z.string().max(255).nullable().describe("Name of person who is primary contact within the business.").optional(), "phoneNumbers": z.array(z.object({ "type": z.string().min(1).describe("The name or id of the phone number type."), "areaCode": z.string().regex(new RegExp("^(\\+)?([0-9]+)$")).max(10).nullable().describe("The area code.").optional(), "number": z.string().regex(new RegExp("^[0-9 ]*$")).max(20).nullable().describe("The number.").optional() }).strict().describe("A phone number.")).describe("List of phone numbers."), "electronicAddresses": z.array(z.object({ "type": z.string().nullable().describe("The name or id of the electronic address type.").optional(), "address": z.string().nullable().describe("The electronic address.").optional() }).strict().describe("An electronic address.")).describe("List of electronic addresses.") }).strict().describe("Details on how to contact the business to update.").describe("Business's contact details.")
}