import { z } from "zod"

export const inputParamsSchema = {
  "id": z.string().describe("The Applicant's ID"),
  "b_id": z.string().min(1).describe("Applicant's identifier"),
  "originalApplicantID": z.string().nullable().describe("Original applicant's identifier").optional(),
  "title": z.string().nullable().describe("Applicant's title").optional(),
  "firstNames": z.string().min(1).describe("Applicant's first names"),
  "preferredFirstName": z.string().nullable().describe("Applicant's preferred first name").optional(),
  "surname": z.string().min(1).describe("Applicant's surname"),
  "previousSurname": z.string().nullable().describe("Applicant's previous surname").optional(),
  "email": z.string().nullable().describe("Applicant's email address").optional(),
  "risk": z.string().nullable().describe("Applicant's risk information").optional(),
  "address": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `address` to the tool, first call the tool `expandSchema` with \"/properties/address\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>").optional(),
  "ward": z.string().nullable().describe("Applicant's ward").optional(),
  "homePhone": z.string().nullable().describe("Applicant's home phone number").optional(),
  "mobile": z.string().nullable().describe("Applicant's mobile phone number").optional(),
  "username": z.string().nullable().describe("Applicant's username").optional(),
  "userID": z.string().nullable().describe("Applicant's user ID").optional(),
  "allowedContactMethods": z.array(z.string()).nullable().describe("List of allowed contact methods for the applicant").optional(),
  "preferredContactMethod": z.string().nullable().describe("Preferred contact method for the applicant").optional(),
  "dateOfBirth": z.string().datetime({ offset: true }).nullable().describe("Applicant's date of birth").optional(),
  "currentAge": z.string().nullable().describe("Applicant's current age").optional(),
  "sex": z.string().nullable().describe("Applicant's gender").optional(),
  "ethnicity": z.string().nullable().describe("Applicant's ethnicity").optional(),
  "niNumber": z.string().nullable().describe("Applicant's National Insurance Number").optional(),
  "learnerReferenceNumber": z.string().nullable().describe("Applicant's Learner Reference Number").optional(),
  "ilrDisability": z.string().nullable().describe("Applicant's Individual Learning Record (ILR) disability status").optional(),
  "lldDs": z.array(z.string()).nullable().describe("List of Learning Difficulties and/or Disabilities (LLDDs) for the applicant").optional(),
  "primaryLLDD": z.string().nullable().describe("Applicant's primary LLDD").optional(),
  "householdSituation": z.array(z.string()).nullable().describe("Household situation for the applicant").optional(),
  "nextOfKinName": z.string().nullable().describe("Name of the next of kin for the applicant").optional(),
  "nextOfKinRelationship": z.string().nullable().describe("Relationship with the next of kin for the applicant").optional(),
  "nextOfKinPhone": z.string().nullable().describe("Phone number of the next of kin for the applicant").optional(),
  "nextOfKinPhone2": z.string().nullable().describe("Second phone number of the next of kin for the applicant").optional(),
  "nextOfKinEmail": z.string().nullable().describe("Email address of the next of kin for the applicant").optional(),
  "otherSystemID": z.string().nullable().describe("ID from another system for the applicant").optional(),
  "providerIdent": z.string().nullable().describe("Provider identifier for the applicant").optional(),
  "mainOfficer": z.string().nullable().describe("Main officer assigned to the applicant").optional(),
  "recruitmentOfficer": z.string().nullable().describe("Recruitment officer assigned to the applicant").optional(),
  "mentorOfficer": z.string().nullable().describe("Mentor officer assigned to the applicant").optional(),
  "plannedStart": z.string().datetime({ offset: true }).nullable().describe("Planned start date for the applicant").optional(),
  "expectedEnd": z.string().datetime({ offset: true }).nullable().describe("Expected end date for the applicant").optional(),
  "countryOfDomicile": z.string().nullable().describe("Country of domicile for the applicant").optional(),
  "site": z.string().nullable().describe("Site information for the applicant").optional(),
  "uln": z.string().nullable().describe("Unique Learner Number (ULN) for the applicant").optional(),
  "restrictedUseIndicator": z.string().nullable().describe("Restricted use indicator for the applicant").optional(),
  "gcseMath": z.string().nullable().describe("GCSE Math qualification status for the applicant").optional(),
  "gcseEnglish": z.string().nullable().describe("GCSE English qualification status for the applicant").optional(),
  "qualificationPlan": z.string().nullable().describe("Qualification plan for the applicant").optional(),
  "act": z.string().nullable().describe("ACT information for the applicant.").optional(),
  "vatStatus": z.string().nullable().describe("VAT status for the applicant").optional(),
  "asStatus": z.string().nullable().describe("AS (Apprenticeship Service) status for the applicant").optional(),
  "asCohort": z.string().nullable().describe("AS (Apprenticeship Service) cohort for the applicant").optional(),
  "bksbUsername": z.string().nullable().describe("BKSB username for the applicant").optional(),
  "employerCode": z.string().nullable().describe("Employer code for the applicant").optional(),
  "recruitmentAgencyCode": z.string().nullable().describe("Recruitment agency code for the applicant").optional(),
  "opportunityID": z.number().int().nullable().describe("Opportunity identifier for the applicant").optional()
}