import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "get_search",
  "toolDescription": "Recherche textuelle",
  "baseUrl": "https://recherche-entreprises.api.gouv.fr",
  "path": "/search",
  "method": "get",
  "security": [],
  "paramsMap": {
    "query": {
      "q": "q",
      "activite_principale": "activite_principale",
      "categorie_entreprise": "categorie_entreprise",
      "code_collectivite_territoriale": "code_collectivite_territoriale",
      "convention_collective_renseignee": "convention_collective_renseignee",
      "code_postal": "code_postal",
      "code_commune": "code_commune",
      "departement": "departement",
      "region": "region",
      "epci": "epci",
      "egapro_renseignee": "egapro_renseignee",
      "est_achats_responsables": "est_achats_responsables",
      "est_alim_confiance": "est_alim_confiance",
      "est_association": "est_association",
      "est_bio": "est_bio",
      "est_collectivite_territoriale": "est_collectivite_territoriale",
      "est_entrepreneur_individuel": "est_entrepreneur_individuel",
      "est_entrepreneur_spectacle": "est_entrepreneur_spectacle",
      "est_ess": "est_ess",
      "est_finess": "est_finess",
      "est_organisme_formation": "est_organisme_formation",
      "est_patrimoine_vivant": "est_patrimoine_vivant",
      "est_qualiopi": "est_qualiopi",
      "est_rge": "est_rge",
      "est_siae": "est_siae",
      "est_service_public": "est_service_public",
      "est_l100_3": "est_l100_3",
      "est_societe_mission": "est_societe_mission",
      "est_uai": "est_uai",
      "etat_administratif": "etat_administratif",
      "id_convention_collective": "id_convention_collective",
      "id_finess": "id_finess",
      "id_rge": "id_rge",
      "id_uai": "id_uai",
      "nature_juridique": "nature_juridique",
      "section_activite_principale": "section_activite_principale",
      "tranche_effectif_salarie": "tranche_effectif_salarie",
      "nom_personne": "nom_personne",
      "prenoms_personne": "prenoms_personne",
      "date_naissance_personne_min": "date_naissance_personne_min",
      "date_naissance_personne_max": "date_naissance_personne_max",
      "type_personne": "type_personne",
      "ca_min": "ca_min",
      "ca_max": "ca_max",
      "resultat_net_min": "resultat_net_min",
      "resultat_net_max": "resultat_net_max",
      "limite_matching_etablissements": "limite_matching_etablissements",
      "minimal": "minimal",
      "include": "include",
      "page": "page",
      "per_page": "per_page"
    }
  },
  inputParamsSchema
}

export default tool