import { z } from "zod"

export const inputParamsSchema = {
  "name": z.string().min(1).describe("Name of the organisation"),
  "alias": z.string().max(60).nullable().describe("Alias of the organisation").optional(),
  "phone": z.string().max(25).nullable().describe("Phone number of the organisation").optional(),
  "mobile": z.string().max(15).nullable().describe("Mobile number of the organisation").optional(),
  "email": z.string().max(100).nullable().describe("Email address of the organisation").optional(),
  "alternateEmail": z.string().max(100).nullable().describe("Alternate email address of the organisation").optional(),
  "address": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `address` to the tool, first call the tool `expandSchema` with \"/properties/address\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>").optional(),
  "ward": z.string().nullable().describe("Ward associated with the organisation").optional(),
  "allowedContactMethods": z.array(z.string()).nullable().describe("List of allowed contact methods for the organisation").optional(),
  "preferredContactMethod": z.string().nullable().describe("Preferred contact method for the organisation").optional(),
  "risk": z.string().max(1).nullable().describe("Risk level associated with the organisation").optional(),
  "website": z.string().url().max(100).nullable().describe("Website of the organisation").optional(),
  "upin": z.string().max(8).nullable().describe("UPIN associated with the organisation").optional(),
  "ukprn": z.string().max(8).nullable().describe("UKPRN associated with the organisation").optional(),
  "edsReference": z.string().max(9).nullable().describe("EDS reference associated with the organisation").optional(),
  "companyRegistrationNumber": z.string().max(8).nullable().describe("Company registration number associated with the organisation").optional(),
  "epaOrganisation": z.string().min(7).max(7).nullable().describe("EPA organisation associated with the organisation").optional(),
  "mainOfficer": z.string().nullable().describe("Main officer associated with the organisation").optional(),
  "mainContact": z.string().nullable().describe("Main contact associated with the organisation").optional(),
  "headOffice": z.string().nullable().describe("Head office associated with the organisation").optional(),
  "status": z.string().nullable().describe("Status of the organisation").optional(),
  "additionalID": z.string().max(50).nullable().describe("Additional ID associated with the organisation").optional(),
  "roles": z.array(z.string()).nullable().describe("List of roles associated with the organisation").optional(),
  "invoiceAddress": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `invoiceAddress` to the tool, first call the tool `expandSchema` with \"/properties/invoiceAddress\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>").optional(),
  "invoiceName": z.string().nullable().describe("Invoice name associated with the organisation").optional(),
  "invoicePhone": z.string().nullable().describe("Invoice phone number associated with the organisation").optional(),
  "invoiceEmail": z.string().nullable().describe("Invoice email address associated with the organisation").optional(),
  "allowMarketing": z.string().nullable().describe("Allow marketing status associated with the organisation").optional(),
  "hasIIP": z.string().nullable().describe("Has IIP status associated with the organisation").optional(),
  "previousTraining": z.string().nullable().describe("Previous training status associated with the organisation").optional(),
  "ethnicMinorityBusiness": z.string().nullable().describe("Ethnic minority business status associated with the organisation").optional(),
  "notes": z.string().nullable().describe("Notes associated with the organisation").optional(),
  "employerSizeBand": z.string().nullable().describe("Employer size band associated with the organisation").optional(),
  "accountingSystemID": z.string().nullable().describe("Accounting system ID associated with the organisation").optional(),
  "vatRegNo": z.string().nullable().describe("VAT registration number associated with the organisation").optional(),
  "employeeCount": z.number().int().nullable().describe("Employee count associated with the organisation").optional(),
  "annualTurnover": z.number().nullable().describe("Annual turnover associated with the organisation").optional()
}