import { z } from "zod"

export const inputParamsSchema = {
  "bookId": z.string().describe("The book's id."),
  "creditNoteId": z.string().describe("The credit note's id."),
  "customer": z.string().min(1).describe("The customer that the credit note will be issued to."),
  "creditNoteDate": z.string().datetime({ offset: true }).min(1).describe("The date of the credit note."),
  "amountTaxStatus": z.enum(["NonTaxed","Inclusive","Exclusive"]).describe("The tax status of an amount.").describe("The amount tax status of the amounts in the credit note."),
  "reference": z.string().nullable().describe("The credit note reference.").optional(),
  "accountsReceivableLedgerAccount": z.string().nullable().describe("The accounts receivable ledger account.\n_Note:_ It is not currently possible to create multiple Accounts Receivable accounts so this field is read-only and will be ignored.").readonly().optional(),
  "classification": z.string().nullable().describe("The classification.").optional(),
  "template": z.string().min(1).describe("The template used to print or email the credit note."),
  "lineItems": z.array(z.object({ "lineNumber": z.number().int().describe("The line number."), "project": z.string().nullable().describe("The id or full name of the project that the line item relates to.\nNote that the full name includes the name(s) of any parent project(s) separated by colons."), "itemDetails": z.object({ "item": z.string().min(1).describe("The id or full name of the item that the line relates to.\nNote that the full name includes the name(s) of any parent item(s) separated by colons."), "price": z.number().nullable().describe("The price of each item including or excluding tax (depending on the `amountTaxStatus`)."), "quantity": z.number().nullable().describe("The quantity purchased.") }).strict().describe("Details of an item used on a credit note line item.").nullable().describe("Details of an item used on an invoice line item.\nThis must be omitted if `accountDetails` have been provided."), "accountDetails": z.object({ "ledgerAccount": z.string().min(1).describe("The id or full name of the ledger account that the line relates to.\nNote that the full name includes the name(s) of any parent account(s) separated by colons."), "quantity": z.number().nullable().describe("The quantity purchased."), "amount": z.number().nullable().describe("The amount including or excluding tax (depending on the `amountTaxStatus`).") }).strict().describe("Details of an account used on a credit note line item.").nullable().describe("Details of an account used on an invoice line item.\nThis must be omitted if `itemDetails` have been provided."), "description": z.string().nullable().describe("The description of the line."), "taxAmount": z.number().nullable().describe("The tax amount."), "taxRate": z.string().nullable().describe("The tax rate."), "taxIsModified": z.boolean().nullable().describe("Whether the tax amount has been modified.").readonly() }).strict().describe("Details of a credit note line item to create or update.")).describe("The individual items that make up the credit note."),
  "notes": z.string().nullable().describe("Notes related to the credit note.").optional()
}