import { z } from "zod"

export const inputParamsSchema = {
  "policyid": z.number().int(),
  "vdom": z.string().describe("Target VDOM (defaults to 'root')").optional(),
  "b_policyid": z.number().int().gte(0).lte(4294967294).describe("Policy ID (0 - 4294967294).").optional(),
  "status": z.enum(["enable","disable"]).describe("Enable or disable this policy.").optional(),
  "name": z.string().max(35).describe("Policy name.").optional(),
  "uuid": z.string().uuid().describe("Universally Unique Identifier (UUID; automatically assigned but can be manually reset).").optional(),
  "srcintf": z.string().describe("Incoming (ingress) interface."),
  "dstintf": z.string().describe("Outgoing (egress) interface."),
  "action": z.enum(["accept","deny","ipsec"]).describe("Policy action (accept/deny/ipsec).").optional(),
  "nat64": z.enum(["enable","disable"]).describe("Enable/disable NAT64.").optional(),
  "nat46": z.enum(["enable","disable"]).describe("Enable/disable NAT46.").optional(),
  "ztna-status": z.enum(["enable","disable"]).describe("Enable/disable zero trust access.").optional(),
  "ztna-device-ownership": z.enum(["enable","disable"]).describe("Enable/disable zero trust device ownership.").optional(),
  "srcaddr": z.string().describe("Source IPv4 address and address group names.").optional(),
  "dstaddr": z.string().describe("Destination IPv4 address and address group names.").optional(),
  "srcaddr6": z.string().describe("Source IPv6 address name and address group names.").optional(),
  "dstaddr6": z.string().describe("Destination IPv6 address name and address group names.").optional(),
  "ztna-ems-tag": z.string().describe("Source ztna-ems-tag names.").optional(),
  "ztna-ems-tag-secondary": z.string().describe("Source ztna-ems-tag-secondary names.").optional(),
  "ztna-tags-match-logic": z.enum(["or","and"]).describe("ZTNA tag matching logic.").optional(),
  "ztna-geo-tag": z.string().describe("Source ztna-geo-tag names.").optional(),
  "internet-service": z.enum(["enable","disable"]).describe("Enable/disable use of Internet Services for this policy. If enabled, destination address and service are not used.").optional(),
  "internet-service-name": z.string().describe("Internet Service name.").optional(),
  "internet-service-group": z.string().describe("Internet Service group name.").optional(),
  "internet-service-custom": z.string().describe("Custom Internet Service name.").optional(),
  "network-service-dynamic": z.string().describe("Dynamic Network Service name.").optional(),
  "internet-service-custom-group": z.string().describe("Custom Internet Service group name.").optional(),
  "internet-service-src": z.enum(["enable","disable"]).describe("Enable/disable use of Internet Services in source for this policy. If enabled, source address is not used.").optional(),
  "internet-service-src-name": z.string().describe("Internet Service source name.").optional(),
  "internet-service-src-group": z.string().describe("Internet Service source group name.").optional(),
  "internet-service-src-custom": z.string().describe("Custom Internet Service source name.").optional(),
  "network-service-src-dynamic": z.string().describe("Dynamic Network Service source name.").optional(),
  "internet-service-src-custom-group": z.string().describe("Custom Internet Service source group name.").optional(),
  "reputation-minimum": z.number().int().gte(0).lte(4294967295).describe("Minimum Reputation to take action.").optional(),
  "reputation-direction": z.enum(["source","destination"]).describe("Direction of the initial traffic for reputation to take effect.").optional(),
  "src-vendor-mac": z.string().describe("Vendor MAC source ID.").optional(),
  "internet-service6": z.enum(["enable","disable"]).describe("Enable/disable use of IPv6 Internet Services for this policy. If enabled, destination address and service are not used.").optional(),
  "internet-service6-name": z.string().describe("IPv6 Internet Service name.").optional(),
  "internet-service6-group": z.string().describe("Internet Service group name.").optional(),
  "internet-service6-custom": z.string().describe("Custom IPv6 Internet Service name.").optional(),
  "internet-service6-custom-group": z.string().describe("Custom Internet Service6 group name.").optional(),
  "internet-service6-src": z.enum(["enable","disable"]).describe("Enable/disable use of IPv6 Internet Services in source for this policy. If enabled, source address is not used.").optional(),
  "internet-service6-src-name": z.string().describe("IPv6 Internet Service source name.").optional(),
  "internet-service6-src-group": z.string().describe("Internet Service6 source group name.").optional(),
  "internet-service6-src-custom": z.string().describe("Custom IPv6 Internet Service source name.").optional(),
  "internet-service6-src-custom-group": z.string().describe("Custom Internet Service6 source group name.").optional(),
  "reputation-minimum6": z.number().int().gte(0).lte(4294967295).describe("IPv6 Minimum Reputation to take action.").optional(),
  "reputation-direction6": z.enum(["source","destination"]).describe("Direction of the initial traffic for IPv6 reputation to take effect.").optional(),
  "rtp-nat": z.enum(["disable","enable"]).describe("Enable Real Time Protocol (RTP) NAT.").optional(),
  "rtp-addr": z.string().describe("Address names if this is an RTP NAT policy."),
  "send-deny-packet": z.enum(["disable","enable"]).describe("Enable to send a reply when a session is denied or blocked by a firewall policy.").optional(),
  "firewall-session-dirty": z.enum(["check-all","check-new"]).describe("How to handle sessions if the configuration of this firewall policy changes.").optional(),
  "schedule": z.string().max(35).describe("Schedule name."),
  "schedule-timeout": z.enum(["enable","disable"]).describe("Enable to force current sessions to end when the schedule object times out. Disable allows them to end from inactivity.").optional(),
  "policy-expiry": z.enum(["enable","disable"]).describe("Enable/disable policy expiry.").optional(),
  "policy-expiry-date": z.string().datetime({ offset: true }).describe("Policy expiry date (YYYY-MM-DD HH:MM:SS).").optional(),
  "policy-expiry-date-utc": z.string().describe("Policy expiry date and time, in epoch format.").optional(),
  "service": z.string().describe("Service and service group names.").optional(),
  "tos-mask": z.string().describe("Non-zero bit positions are used for comparison while zero bit positions are ignored.").optional(),
  "tos": z.string().describe("ToS (Type of Service) value used for comparison.").optional(),
  "tos-negate": z.enum(["enable","disable"]).describe("Enable negated TOS match.").optional(),
  "anti-replay": z.enum(["enable","disable"]).describe("Enable/disable anti-replay check.").optional(),
  "tcp-session-without-syn": z.enum(["all","data-only","disable"]).describe("Enable/disable creation of TCP session without SYN flag.").optional(),
  "geoip-anycast": z.enum(["enable","disable"]).describe("Enable/disable recognition of anycast IP addresses using the geography IP database.").optional(),
  "geoip-match": z.enum(["physical-location","registered-location"]).describe("Match geography address based either on its physical location or registered location.").optional(),
  "dynamic-shaping": z.enum(["enable","disable"]).describe("Enable/disable dynamic RADIUS defined traffic shaping.").optional(),
  "passive-wan-health-measurement": z.enum(["enable","disable"]).describe("Enable/disable passive WAN health measurement. When enabled, auto-asic-offload is disabled.").optional(),
  "utm-status": z.enum(["enable","disable"]).describe("Enable to add one or more security profiles (AV, IPS, etc.) to the firewall policy.").optional(),
  "inspection-mode": z.enum(["proxy","flow"]).describe("Policy inspection mode (Flow/proxy). Default is Flow mode.").optional(),
  "http-policy-redirect": z.enum(["enable","disable"]).describe("Redirect HTTP(S) traffic to matching transparent web proxy policy.").optional(),
  "ssh-policy-redirect": z.enum(["enable","disable"]).describe("Redirect SSH traffic to matching transparent proxy policy.").optional(),
  "ztna-policy-redirect": z.enum(["enable","disable"]).describe("Redirect ZTNA traffic to matching Access-Proxy proxy-policy.").optional(),
  "webproxy-profile": z.string().max(63).describe("Webproxy profile name.").optional(),
  "profile-type": z.enum(["single","group"]).describe("Determine whether the firewall policy allows security profile groups or single profiles only.").optional(),
  "profile-group": z.string().max(35).describe("Name of profile group.").optional(),
  "profile-protocol-options": z.string().max(35).describe("Name of an existing Protocol options profile.").optional(),
  "ssl-ssh-profile": z.string().max(35).describe("Name of an existing SSL SSH profile.").optional(),
  "av-profile": z.string().max(35).describe("Name of an existing Antivirus profile.").optional(),
  "webfilter-profile": z.string().max(35).describe("Name of an existing Web filter profile.").optional(),
  "dnsfilter-profile": z.string().max(35).describe("Name of an existing DNS filter profile.").optional(),
  "emailfilter-profile": z.string().max(35).describe("Name of an existing email filter profile.").optional(),
  "dlp-profile": z.string().max(35).describe("Name of an existing DLP profile.").optional(),
  "file-filter-profile": z.string().max(35).describe("Name of an existing file-filter profile.").optional(),
  "ips-sensor": z.string().max(35).describe("Name of an existing IPS sensor.").optional(),
  "application-list": z.string().max(35).describe("Name of an existing Application list.").optional(),
  "voip-profile": z.string().max(35).describe("Name of an existing VoIP (voipd) profile.").optional(),
  "ips-voip-filter": z.string().max(35).describe("Name of an existing VoIP (ips) profile.").optional(),
  "sctp-filter-profile": z.string().max(35).describe("Name of an existing SCTP filter profile.").optional(),
  "diameter-filter-profile": z.string().max(35).describe("Name of an existing Diameter filter profile.").optional(),
  "virtual-patch-profile": z.string().max(35).describe("Name of an existing virtual-patch profile.").optional(),
  "icap-profile": z.string().max(35).describe("Name of an existing ICAP profile.").optional(),
  "cifs-profile": z.string().max(35).describe("Name of an existing CIFS profile.").optional(),
  "videofilter-profile": z.string().max(35).describe("Name of an existing VideoFilter profile.").optional(),
  "waf-profile": z.string().max(35).describe("Name of an existing Web application firewall profile.").optional(),
  "ssh-filter-profile": z.string().max(35).describe("Name of an existing SSH filter profile.").optional(),
  "casb-profile": z.string().max(35).describe("Name of an existing CASB profile.").optional(),
  "logtraffic": z.enum(["all","utm","disable"]).describe("Enable or disable logging. Log all sessions or security profile sessions.").optional(),
  "logtraffic-start": z.enum(["enable","disable"]).describe("Record logs when a session starts.").optional(),
  "log-http-transaction": z.enum(["enable","disable"]).describe("Enable/disable HTTP transaction log.").optional(),
  "capture-packet": z.enum(["enable","disable"]).describe("Enable/disable capture packets.").optional(),
  "auto-asic-offload": z.enum(["enable","disable"]).describe("Enable/disable policy traffic ASIC offloading.").optional(),
  "wanopt": z.enum(["enable","disable"]).describe("Enable/disable WAN optimization.").optional(),
  "wanopt-detection": z.enum(["active","passive","off"]).describe("WAN optimization auto-detection mode.").optional(),
  "wanopt-passive-opt": z.enum(["default","transparent","non-transparent"]).describe("WAN optimization passive mode options. This option decides what IP address will be used to connect server.").optional(),
  "wanopt-profile": z.string().max(35).describe("WAN optimization profile."),
  "wanopt-peer": z.string().max(35).describe("WAN optimization peer."),
  "webcache": z.enum(["enable","disable"]).describe("Enable/disable web cache.").optional(),
  "webcache-https": z.enum(["disable","enable"]).describe("Enable/disable web cache for HTTPS.").optional(),
  "webproxy-forward-server": z.string().max(63).describe("Webproxy forward server name.").optional(),
  "traffic-shaper": z.string().max(35).describe("Traffic shaper.").optional(),
  "traffic-shaper-reverse": z.string().max(35).describe("Reverse traffic shaper.").optional(),
  "per-ip-shaper": z.string().max(35).describe("Per-IP traffic shaper.").optional(),
  "nat": z.enum(["enable","disable"]).describe("Enable/disable source NAT.").optional(),
  "pcp-outbound": z.enum(["enable","disable"]).describe("Enable/disable PCP outbound SNAT.").optional(),
  "pcp-inbound": z.enum(["enable","disable"]).describe("Enable/disable PCP inbound DNAT.").optional(),
  "pcp-poolname": z.string().describe("PCP pool names.").optional(),
  "permit-any-host": z.enum(["enable","disable"]).describe("Accept UDP packets from any host.").optional(),
  "permit-stun-host": z.enum(["enable","disable"]).describe("Accept UDP packets from any Session Traversal Utilities for NAT (STUN) host.").optional(),
  "fixedport": z.enum(["enable","disable"]).describe("Enable to prevent source NAT from changing a session's source port.").optional(),
  "port-preserve": z.enum(["enable","disable"]).describe("Enable/disable preservation of the original source port from source NAT if it has not been used.").optional(),
  "ippool": z.enum(["enable","disable"]).describe("Enable to use IP Pools for source NAT.").optional(),
  "poolname": z.string().describe("IP Pool names.").optional(),
  "poolname6": z.string().describe("IPv6 pool names.").optional(),
  "session-ttl": z.string().describe("TTL in seconds for sessions accepted by this policy (0 means use the system default session TTL).").optional(),
  "vlan-cos-fwd": z.number().int().gte(0).lte(7).describe("VLAN forward direction user priority: 255 passthrough, 0 lowest, 7 highest.").optional(),
  "vlan-cos-rev": z.number().int().gte(0).lte(7).describe("VLAN reverse direction user priority: 255 passthrough, 0 lowest, 7 highest.").optional(),
  "inbound": z.enum(["enable","disable"]).describe("Policy-based IPsec VPN: only traffic from the remote network can initiate a VPN.").optional(),
  "outbound": z.enum(["enable","disable"]).describe("Policy-based IPsec VPN: only traffic from the internal network can initiate a VPN.").optional(),
  "natinbound": z.enum(["enable","disable"]).describe("Policy-based IPsec VPN: apply destination NAT to inbound traffic.").optional(),
  "natoutbound": z.enum(["enable","disable"]).describe("Policy-based IPsec VPN: apply source NAT to outbound traffic.").optional(),
  "fec": z.enum(["enable","disable"]).describe("Enable/disable Forward Error Correction on traffic matching this policy on a FEC device.").optional(),
  "wccp": z.enum(["enable","disable"]).describe("Enable/disable forwarding traffic matching this policy to a configured WCCP server.").optional(),
  "ntlm": z.enum(["enable","disable"]).describe("Enable/disable NTLM authentication.").optional(),
  "ntlm-guest": z.enum(["enable","disable"]).describe("Enable/disable NTLM guest user access.").optional(),
  "ntlm-enabled-browsers": z.string().describe("HTTP-User-Agent value of supported browsers.").optional(),
  "fsso-agent-for-ntlm": z.string().max(35).describe("FSSO agent to use for NTLM authentication.").optional(),
  "groups": z.string().describe("Names of user groups that can authenticate with this policy.").optional(),
  "users": z.string().describe("Names of individual users that can authenticate with this policy.").optional(),
  "fsso-groups": z.string().describe("Names of FSSO groups.").optional(),
  "auth-path": z.enum(["enable","disable"]).describe("Enable/disable authentication-based routing.").optional(),
  "disclaimer": z.enum(["enable","disable"]).describe("Enable/disable user authentication disclaimer.").optional(),
  "email-collect": z.enum(["enable","disable"]).describe("Enable/disable email collection.").optional(),
  "vpntunnel": z.string().max(35).describe("Policy-based IPsec VPN: name of the IPsec VPN Phase 1."),
  "natip": z.string().describe("Policy-based IPsec VPN: source NAT IP address for outgoing traffic.").optional(),
  "match-vip": z.enum(["enable","disable"]).describe("Enable to match packets that have had their destination addresses changed by a VIP.").optional(),
  "match-vip-only": z.enum(["enable","disable"]).describe("Enable/disable matching of only those packets that have had their destination addresses changed by a VIP.").optional(),
  "diffserv-copy": z.enum(["enable","disable"]).describe("Enable to copy packet's DiffServ values from session's original direction to its reply direction.").optional(),
  "diffserv-forward": z.enum(["enable","disable"]).describe("Enable to change packet's DiffServ values to the specified diffservcode-forward value.").optional(),
  "diffserv-reverse": z.enum(["enable","disable"]).describe("Enable to change packet's reverse (reply) DiffServ values to the specified diffservcode-rev value.").optional(),
  "diffservcode-forward": z.string().describe("Change packet's DiffServ to this value.").optional(),
  "diffservcode-rev": z.string().describe("Change packet's reverse (reply) DiffServ to this value.").optional(),
  "tcp-mss-sender": z.number().int().gte(0).lte(65535).describe("Sender TCP maximum segment size (MSS).").optional(),
  "tcp-mss-receiver": z.number().int().gte(0).lte(65535).describe("Receiver TCP maximum segment size (MSS).").optional(),
  "comments": z.string().max(1023).describe("Comment.").optional(),
  "auth-cert": z.string().max(35).describe("HTTPS server certificate for policy authentication.").optional(),
  "auth-redirect-addr": z.string().max(63).describe("HTTP-to-HTTPS redirect address for firewall authentication.").optional(),
  "redirect-url": z.string().max(1023).describe("URL users are directed to after seeing and accepting the disclaimer or authenticating.").optional(),
  "identity-based-route": z.string().max(35).describe("Name of identity-based routing rule.").optional(),
  "block-notification": z.enum(["enable","disable"]).describe("Enable/disable block notification.").optional(),
  "custom-log-fields": z.string().describe("Custom fields to append to log messages for this policy.").optional(),
  "replacemsg-override-group": z.string().max(35).describe("Override the default replacement message group for this policy.").optional(),
  "srcaddr-negate": z.enum(["enable","disable"]).describe("When enabled srcaddr specifies what the source address must NOT be.").optional(),
  "srcaddr6-negate": z.enum(["enable","disable"]).describe("When enabled srcaddr6 specifies what the source address must NOT be.").optional(),
  "dstaddr-negate": z.enum(["enable","disable"]).describe("When enabled dstaddr specifies what the destination address must NOT be.").optional(),
  "dstaddr6-negate": z.enum(["enable","disable"]).describe("When enabled dstaddr6 specifies what the destination address must NOT be.").optional(),
  "service-negate": z.enum(["enable","disable"]).describe("When enabled service specifies what the service must NOT be.").optional(),
  "internet-service-negate": z.enum(["enable","disable"]).describe("When enabled internet-service specifies what the service must NOT be.").optional(),
  "internet-service-src-negate": z.enum(["enable","disable"]).describe("When enabled internet-service-src specifies what the service must NOT be.").optional(),
  "internet-service6-negate": z.enum(["enable","disable"]).describe("When enabled internet-service6 specifies what the service must NOT be.").optional(),
  "internet-service6-src-negate": z.enum(["enable","disable"]).describe("When enabled internet-service6-src specifies what the service must NOT be.").optional(),
  "timeout-send-rst": z.enum(["enable","disable"]).describe("Enable/disable sending RST packets when TCP sessions expire.").optional(),
  "captive-portal-exempt": z.enum(["enable","disable"]).describe("Enable to exempt some users from the captive portal.").optional(),
  "decrypted-traffic-mirror": z.string().max(35).describe("Decrypted traffic mirror.").optional(),
  "dsri": z.enum(["enable","disable"]).describe("Enable DSRI to ignore HTTP server responses.").optional(),
  "radius-mac-auth-bypass": z.enum(["enable","disable"]).describe("Enable MAC authentication bypass. The bypassed MAC address must be received from RADIUS server.").optional(),
  "radius-ip-auth-bypass": z.enum(["enable","disable"]).describe("Enable IP authentication bypass. The bypassed IP address must be received from RADIUS server.").optional(),
  "delay-tcp-npu-session": z.enum(["enable","disable"]).describe("Enable TCP NPU session delay to guarantee packet order of 3-way handshake.").optional(),
  "vlan-filter": z.string().describe("VLAN ranges to allow").optional(),
  "sgt-check": z.enum(["enable","disable"]).describe("Enable/disable security group tags (SGT) check.").optional(),
  "sgt": z.string().describe("Security group tags.").optional()
}