import { z } from "zod"

export const inputParamsSchema = {
  "config_id": z.string(),
  "name": z.union([z.string().min(3).max(100), z.null()]).optional(),
  "description": z.union([z.string().max(500), z.null()]).optional(),
  "trigger_type": z.union([z.enum(["time_based","sensor_based"]).describe("Tipos de trigger para totalização"), z.null()]).optional(),
  "operation": z.union([z.enum(["sum","count","average","min","max","integral","time_running","time_stopped","time_in_state","state_changes","uptime_percentage","energy_consumption","energy_cost"]).describe("Operações de totalização disponíveis"), z.null()]).optional(),
  "time_interval": z.union([z.enum(["minute","hour","day","week","month"]).describe("Intervalos de tempo para totalização"), z.null()]).optional(),
  "time_interval_value": z.union([z.number().int().gte(1).lte(60), z.null()]).optional(),
  "window_type": z.union([z.enum(["rolling","fixed_hourly","fixed_daily","fixed_weekly","fixed_monthly","custom_shift","custom_period"]).describe("Tipos de janela de totalização"), z.null()]).optional(),
  "fixed_hour_start": z.union([z.number().int().gte(0).lte(23), z.null()]).optional(),
  "fixed_hour_end": z.union([z.number().int().gte(0).lte(23), z.null()]).optional(),
  "daily_start_time": z.union([z.string().regex(new RegExp("^([01]?[0-9]|2[0-3]):[0-5][0-9]$")), z.null()]).optional(),
  "daily_end_time": z.union([z.string().regex(new RegExp("^([01]?[0-9]|2[0-3]):[0-5][0-9]$")), z.null()]).optional(),
  "weekly_start_day": z.union([z.number().int().gte(0).lte(6), z.null()]).optional(),
  "weekly_end_day": z.union([z.number().int().gte(0).lte(6), z.null()]).optional(),
  "monthly_start_day": z.union([z.number().int().gte(1).lte(31), z.null()]).optional(),
  "monthly_end_day": z.union([z.number().int().gte(1).lte(31), z.null()]).optional(),
  "custom_shifts": z.union([z.array(z.object({ "name": z.string().describe("Nome do turno"), "start": z.string().regex(new RegExp("^([01]?[0-9]|2[0-3]):[0-5][0-9]$")).describe("Horário de início (HH:MM)"), "end": z.string().regex(new RegExp("^([01]?[0-9]|2[0-3]):[0-5][0-9]$")).describe("Horário de fim (HH:MM)") }).describe("Schema para turno customizado")), z.null()]).optional(),
  "window_timezone": z.union([z.string(), z.null()]).optional(),
  "allow_overlap": z.union([z.boolean(), z.null()]).optional(),
  "gap_tolerance_minutes": z.union([z.number().int().gte(0).lte(60), z.null()]).optional(),
  "running_condition": z.union([z.string(), z.null()]).optional(),
  "running_threshold": z.union([z.number(), z.null()]).optional(),
  "state_values": z.union([z.record(z.string()), z.null()]).optional(),
  "idle_timeout_minutes": z.union([z.number().int().gte(1).lte(60), z.null()]).optional(),
  "equipment_power_kw": z.union([z.number().gt(0), z.null()]).optional(),
  "energy_price_kwh": z.union([z.number().gt(0), z.null()]).optional(),
  "energy_tariff_config": z.union([z.record(z.any()), z.null()]).optional(),
  "trigger_tag_id": z.union([z.string().uuid(), z.null()]).optional(),
  "trigger_condition": z.union([z.enum(["==","!=",">",">=","<","<="]).describe("Condições para trigger baseado em sensor"), z.null()]).optional(),
  "trigger_value": z.union([z.number(), z.null()]).optional(),
  "reset_on_trigger": z.union([z.boolean(), z.null()]).optional(),
  "min_samples": z.union([z.number().int().gte(1), z.null()]).optional(),
  "quality_filter": z.union([z.string(), z.null()]).optional(),
  "store_intermediate_values": z.union([z.boolean(), z.null()]).optional(),
  "precision_digits": z.union([z.number().int().gte(0).lte(6), z.null()]).optional(),
  "active": z.union([z.boolean(), z.null()]).optional()
}