import { z } from "zod"

export const inputParamsSchema = {
  "treet_id": z.string().uuid(),
  "treet": z.union([z.object({ "valid_from": z.union([z.string(), z.null()]).optional(), "expires_at": z.union([z.string(), z.null()]).optional(), "schedule_id": z.union([z.string().uuid(), z.null()]).optional(), "total_redeem_limit": z.union([z.number().int().gte(0).lte(100000), z.null()]).optional(), "user_redeem_limit": z.union([z.number().int().gte(0).lte(100000), z.null()]).optional(), "share_redeem_limit": z.union([z.number().int().gte(0).lte(100000), z.null()]).describe("Gives an error if set to greater than user_limit.").optional(), "is_sharable": z.union([z.boolean(), z.null()]).optional(), "total_share_limit": z.union([z.number().int().gte(0).lte(100000), z.null()]).optional(), "user_share_limit": z.union([z.number().int().gte(0).lte(100000), z.null()]).optional(), "branch_limit": z.union([z.number().int().gte(0).lt(10), z.null()]).optional(), "show_redeems_left": z.union([z.boolean(), z.null()]).describe("If false, UI should hide redeems left for app users.").optional(), "allow_bookings": z.union([z.boolean(), z.null()]).optional(), "hidden_until": z.union([z.string(), z.null()]).describe("Hidden until this date. If None, then the treet is always shown.").optional(), "state": z.union([z.enum(["active","inactive","archived"]).describe("The state of a Treet.\n\n- `active`: The Treet is active.\n- `inactive`: It cannot be redeemed but should be shown in main stats.\n- `archived`: It cannot be redeemed and should not be shown in main stats.\n\nIf the owner wants to never see stats for the Treet again,\nthen they should delete it instead of archiving it."), z.null()]).optional(), "redeem_validation_type": z.union([z.enum(["naive","in_person","external"]).describe("Redeem validation type for a Treet.\n\nWhen a Redeem is validated, then it is \"used\".\n\n- `naive`: The redeem is automatically verified, when the Treet is redeemed.\n- `in_person`: In person validation\n- `external`: (not used) external validation, through a website or another app etc."), z.null()]).describe("Type of redeem validation.").optional(), "cooldown": z.union([z.number().int().gte(120).lte(315576000), z.null()]).describe("Cooldown in seconds. If not set, no cooldown.").optional(), "allow_reservations": z.union([z.boolean(), z.null()]).describe("If false, reservations button will be hidden on app.").optional() }).strict().describe("Update DTO for client."), z.null()]).optional(),
  "treet_version": z.union([z.object({ "cover_image_id": z.union([z.string().uuid(), z.null()]).optional(), "title": z.union([z.string().min(1).max(100), z.null()]).optional(), "description": z.union([z.string().max(2000), z.null()]).optional(), "additional_info": z.union([z.string().max(2000), z.null()]).optional(), "website_url": z.union([z.string().max(2047), z.null()]).optional(), "instructions": z.union([z.string().max(2000), z.null()]).optional(), "static_code": z.union([z.string().max(255), z.null()]).optional(), "code_type": z.union([z.enum(["no_code","static","upload"]).describe("Code type for Treet.\n\n- `no_code`: Treet does not have a code.\n- `static`: Single static code is used for all Treets.\n- `upload`: Each Redeem gets a unique code from one of the uploaded codes."), z.null()]).optional(), "code_display_type": z.union([z.enum(["none","text","qrcode","barcode"]).describe("How a code of a Treet is displayed.\n\n- `none`: Do not display the code\n- `text`: Display code as text\n- `qrcode`: Display as QR code\n- `barcode`: display as barcode"), z.null()]).optional() }).strict().describe("Update DTO for client."), z.null()]).optional(),
  "gallery_ids": z.union([z.array(z.string().uuid()).max(10), z.null()]).optional(),
  "locations": z.union([z.array(z.object({ "address": z.string().describe("This can be whatever format client decides on."), "location": z.string().describe("Must be a point using format `(latitude,longitude)`.") }).describe("DTO for location data.")).max(10), z.null()]).optional(),
  "category_ids": z.union([z.array(z.string().uuid()).max(3), z.null()]).optional()
}